import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import FooterSection from "./Components/Sections/FooterSection/FooterSection";
import "./globals.css";
import GTMInitializer from "./GTMInitializer";
import NavSection from "./Components/Sections/NavSection/NavSection";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GTMInitializer />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={rubik.className}>
        <NavSection />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
